allowBuilds:
  '@swc/core': true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.57939439ddcb16d9f54ebf7d41432893182ee46d
  vite-plus: 0.0.0-commit.57939439ddcb16d9f54ebf7d41432893182ee46d
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - unrs-resolver
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
